site_name: Projekte
site_url: https://roadrider42.github.io/mkdocs-demo/
theme:
  name: material
  features:
    - navigation.sections  # Gruppiert Seiten in Abschnitte
    - navigation.expand   # Erweitert alle Untermenüs standardmäßig
    - navigation.top      # Fügt einen "Zurück zum Anfang"-Button hinzu
nav:
  - Home: index.md
  - Medienstudio2: Medienstudio2.md
  - Medienstudio2: Medienstudio2.md